### ISSUE TITLE
Snapshot meta-peristence - storing collections of per-world and per-module' snapshot ids

### ISSUE THREAD

**Issue by miloszm** [dusk-network/hatchery#38] opened 2022-08-11 15:13 UTC
**Describe what you want implemented** 
In addition to actual snapshots, also lists of snapshot ids need to be stored. This includes world snapshot ids for the global context, and module snapshot ids for the module contexts. Snapshots should be "restorable" with no regard if the system was restarted or not after they were created.

**Describe "Why" this is needed**
We need to be able to recreate snapshots after the system is shut down and restarted. Currently snapshots will be forgotten when the system restarts.

**Describe alternatives you've considered**
There is really no alternative.

**Additional context**
N/A

**Comment by ureeves** [comment] 2022-09-29 07:45
Closing as a duplicate of #50 together with @miloszm

**Closed by ureeves** 2022-09-29 07:45 UTC
Labels: mark:next, team:Core
